version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  front:
    build: ./front
    restart: always
    env_file: ./front/.env
    ports:
      - 3000:3000
    links:
      - mongo
      - beckend

  beckend:
    restart: always
    build: ./beckend
    ports:
      - '3020:3020'
    env_file: ./beckend/.env
    links:
      - mongo
